Redid builtin_cd to return int
Eagle-9/crash pull request #35
Opened 2024-02-15 17:06 UTC by sheepman39

2024-02-15 21:55 UTC, dennorak requested changes
See comments, but basically let's pass a `char**` instead of `std::string`

2024-02-15 21:55 UTC, dennorak commented on src/impl.cc
> +    int (*function_pointer)(int argc, std::string *argv);
This should be `int argc, char** argv`

2024-02-15 21:55 UTC, dennorak commented on src/impl.cc
> +int builtin_cd(int argc, std::string *argv)
same as the other comment

2024-02-18 18:17 UTC, sheepman39 commented
Should be good to merge now.

2024-02-19 19:13 UTC, merged