75 help command
Eagle-9/crash pull request #91
Opened 2024-03-15 20:09 UTC by sheepman39

2024-03-16 19:27 UTC, dennorak requested changes

2024-03-16 19:27 UTC, dennorak commented on src/builtin/exit.cc
> +        std::cout << "exit: exit" << std::endl;
Should there be a help message here that's not an empty argument list?

2024-03-16 19:27 UTC, dennorak commented on src/builtin/help.cc
> +    else if (strcmp(argv[1], "-h") == 0)
This should be `if (argc == 1 || strcmp(argv[1], "-h") == 0)`, instead of having two of the same case

2024-03-16 19:27 UTC, dennorak commented on src/builtin/help.cc
> +        std::cout << "not a known command. Did you mean help -h or help -H ?" << std::endl; // not a known command
would be an unknown flag, not command. The command is `help`

2024-03-16 19:27 UTC, dennorak commented on src/builtin/help.cc
> +            char **full_cmd = new char *[2];
Why use `new`? you can just initialize a new array on the stack, more memory safe

2024-03-16 19:27 UTC, dennorak commented on src/builtin/help.cc
> +            std::cout << argv[1] << " is not a valid command" << std::endl;
Same as above, this would be an invalid argument, not command

2024-03-16 20:20 UTC, sheepman39 commented on src/builtin/exit.cc
> +        std::cout << "exit: exit" << std::endl;
For the help command I am trying to keep it consistent in the format of `cmd: cmd [args]`. If you think something else should be changed, let me know.

2024-03-16 20:21 UTC, sheepman39 commented on src/builtin/help.cc
> +    else if (strcmp(argv[1], "-h") == 0)
Forgot about that I split it up for debugging. Will revise.

2024-03-16 20:21 UTC, sheepman39 commented on src/builtin/help.cc
> +        std::cout << "not a known command. Did you mean help -h or help -H ?" << std::endl; // not a known command
Ok.

2024-03-16 20:22 UTC, sheepman39 commented on src/builtin/help.cc
> +            std::cout << argv[1] << " is not a valid command" << std::endl;
Ok.

2024-03-16 20:22 UTC, dennorak commented on src/builtin/exit.cc
> +        std::cout << "exit: exit" << std::endl;
I see that, I'm saying should there also be a description of the command?

2024-03-16 20:23 UTC, sheepman39 commented on src/builtin/help.cc
> +            char **full_cmd = new char *[2];
Since I always mess up the syntax for stuff like this, I found it easier to just keep it on the heap. Especially considering that the two sub-arrays are two different lengths.

2024-03-16 20:24 UTC, sheepman39 commented on src/builtin/exit.cc
> +        std::cout << "exit: exit" << std::endl;
Ah I see, I'll keep this just as the -h flag and add something more for -H

2024-03-18 02:01 UTC, sheepman39 commented
Latest commits should address requested changes.

2024-03-18 19:53 UTC, dennorak approved these changes
👍

2024-03-18 19:53 UTC, dennorak commented on src/builtin/help.cc
> +            // to avoid using the heap, we will create an array of pointers
I appreciate the effort, though you didn't have to change this. You made a good point the first time of "who cares", so I'm cool w either way

2024-03-18 19:54 UTC, merged

2024-03-18 19:54 UTC, sheepman39 commented on src/builtin/help.cc
> +            // to avoid using the heap, we will create an array of pointers
Eh I learned something new with C++ and it took like 20 minutes and its more safe so win-win.